- components/OutcomeModal.vue
- components/PromiseModal.vue
- components/RenegeModal.vue
- components/ShareModal.vue
There are quite a few element selectors in the code which is bad practice.  This is a first attempt at removing a few and using bootstrap selectors in their place.  The colour ones will have to wait until there is a standardised colour system in place.
> Remove some element selectors as they aren't good practice

- assets/css/global.scss
- components/Postcode.vue
Use a deep selector so that the class can be used in a child component and not removed by the postcss process.
See here for a description
[https://vue-loader.vuejs.org/guide/scoped-css.html#child-component-root-elements](url)
> Add a deep selector so that the class can be used in a child component

- assets/css/global.scss
- components/Autocomplete.vue
This class is only used with the autocomplete component so it should live with it.  There is then no issues with postcss removing it either.
> Move iteminp class to where it is used

- assets/css/global.scss
- components/ChatListEntry.vue
- components/ChatPopup.vue
This fixes the ellipsis issue on the chat name.  To display an ellipsis you need a width. The issue was a width a set but the container was inline and so the width had no effect.
> To display an ellipsis for overflow the container needs a width.

- components/Postcode.vue
- pages/find/whatisit.vue
- pages/give/whatisit.vue
This is a bit of a redesign of the give page controls. Because of the narrow nature of the main section of the page, the design with the postcode, group, add and delete buttons in one row rapidly breaks.
The add and delete buttons aren`t actually directly related to an individual card and so they can be taken out into their own section.  That gives the whole area some breathing space and works at all breakpoints.
A further step would be to expand out the group control to fill up the remaining space in the row as many of the groups are too long to fit as it is.
Take a look and let me know what you think.
> Fix up the design of the options and buttons.

- assets/css/_color-vars.scss
- components/StartEndDate.vue
Fix the date layout in all breakpoints.
This resolves the following problems:
- I`ve moved the labels above the fields as this gives them more space as previously they would break almost instantly on smaller screens. Having the label about the field helps people scan better.
- Was previously set up as a bootstrap card which it isn`t really
- Remove the placeholders - Generally placeholders aren`t great for various reasons like accessibility, people can more easily scan for empty fields rather than fields already containing stuff, auto translate tools won`t translate them, when you start typing you lose the text etc.  The other fields should probably move the placeholder text into smaller text above or below the field
> Sort out the date layout so it works across all breakpoints

- assets/css/global.scss
- layouts/default.vue
More clearing out of global styles.  Move the notification classes out of global and into the layout component.
Can the following element be removed?
`<a class="d-none dropdown-item" />`
Was it just added to sort out the previous `scoped` issue?  If so then I`ll remove it and re-test.
> Move notification specific classes into their component.

- plugins/vuex-persistedstate.js
Addressing the TODO item:
> TODO Can we force it to happen before moving away from the page?  There's a window where if you sign in, then reload rapidly, you'll be logged out.  Similarly for other data changes.
This uses the "beforeunload" page event to add a hook to save the latest state.
> Save state on page unload

- components/SidebarLeft.vue
Fix the TODO
justify-content can only be used on the parent container and not the individual items so they weren`t having any effect.  There is currently no justify-self in flexbox and so an alternative solution is to add an auto top margin to the bottom box.
> Fix the issue with the bottom box floating to the top

- components/CommunityEventModal.vue
- components/StartEndCollection.vue
- components/StartEndDate.vue
- pages/communityevents/_id.vue
The previous code would make a huge number of `AddDate` API calls. I _think_ this was actually because there was some `JSON.stringify()` calls being done on the start/end date object, which it was then iterating over. Not sure... I didn't look too deeply into that.
I had also noticed that the "event" data on the `CommunityEventModal` was not reactive (i.e. trying to print or watch values did not work). This was because the event object was defined as `{}` with no attributes, but used in the forms like `event.title`. This does not allow vue reactivity to work. So, the new approach is to define a default value function that gives null values to all the attributes that be used.
I reworked it to use `v-model` attributes where possible, this results in quite a lot of code/logic going away as …
> Fix saving/editing community event dates

- components/CommunityEventModal.vue
- components/GroupRememberSelect.vue
- components/GroupSelect.vue
- components/VolunteerOpportunityModal.vue
- mixins/createGroupRoute.js
- pages/communities.vue
- pages/help.vue
- pages/unsubscribe.vue
- store/communityevents.js
This fixes the issue that the GroupRememberSelect would give too much importance to the remember value. When editing an existing event, it should use the value from the event.
This changes it so that the remember value is only used where the value is not set (i.e. falsey) on the outer component, so it means setting groupid to null in the pages that use this component is required to get the correct behaviour.
> Refine GroupRememberSelect to work in edit forms

- layouts/default.vue
- nuxt.config.js
I used the _nuxt way_ with the [head()](https://nuxtjs.org/api/pages-head/) option. I kept it in the layout, given the counts are already calculated there, and the `head()` bit needs to go into a page/layout.
I also refactored the method to calculate the chat count using `reduce` function, seems perfect for that use case, but sometimes people don't understand how `reduce` works, what do you think?
Awaiting input on formatting for the title.
> Show notification count in page title

- components/CommunityEventModal.vue
- components/StartEndCollection.vue
- components/VolunteerOpportunityModal.vue
- pages/volunteering/_id.vue
The main change is to correctly use `v-model` when using `StartEndCollection`. I had done this for community events, but omitted to do it for volunteerings.
Other related changes are:
- create default event for volunteering with all the fields nulled (allows reactivity to work as vue intended, matches how it works for community events)
- add a few extra fields to the default function for events and volunteerings (id and canmodify), probably not important, as they are only set for data that comes back from the API I think, but defining the fields up front seems nice to me (specifies what is available)
- use lodash's `cloneDeep` instead of `JSON.parse(JSON.stringify(data))` (which has data loss when using it with dates, which we do, see [explanation](https://stackoverflow.com/a/122704)), …
> Fix start end collection usage

- components/LoginModal.vue
- pages/index.vue
The Login Modal would not allow you to open it again after being closed. 
The computed `showModal` now has a setter and a getter to fix this issue.
> Fix Login Modal

- package-lock.json
- package.json
See https://github.com/sass/node-sass/issues/2765.
Although I also notice a large number of `package-lock.json` changes, I think our nodejs versions might be quite different, which makes that file churn a lot :/
> Upgrade node-sass to work with node v13

- layouts/default.vue
- nuxt.config.js
Remove the nuxt loading bar as per the TODO.
I've removed the bar in this PR but you can also style it or create your own.
[(https://nuxtjs.org/api/configuration-loading/)]
I'm not sure that it's particularly standard to have a page loading bar.  The browser will tell you the page is loading.  If the page is loading slowly enough to require telling the user then the page load speed should probably be increased. i.e. the task should be to investigate how to make the page load faster (or have a faster perceived load time e.g. image placeholders, load above the fold stuff first etc.)
> Remove the nuxt loading bar

- components/NewsThread.vue
This PR is basically to replace the b-alert with a notice-message component.
The reason this was tricky was because the edit dropdown on the card was floated to the right but the alert component had a higher z index so was shown over it.  The notice component didn't and so the dropdown displayed over it.
Basically I've refactored the news section to use dynamic components and now it only displays the dropdown if the news type is known.
Thoughts, suggestions and abuse please.... :-)
> Use the notice component instead of the b-alert

- layouts/default.vue
Sort out one of the TODOs.
At the moment the chats have the button "Mark all read" and the notifcations have the button "Mark all as read".  Should these be the same for consistency?
> Align the mark all read button to the right

- layouts/default.vue
- store/notifications.js
This PR deals with the TODO in default.vue regarding the Vue warning about duplicates in the notifications list.
The duplicates in default.vue notifications were coming from the store.  Each time the 'list' store action was called it was calling the 'add' mutation.  The lodash 'union' method combined the old and new notification data together.  Union only removes duplicate on primitive values and so the duplicate objects weren't being removed.  I've added an comparator function in to compare the IDs.
You might want to take a proper look at this solution as I'm not that familiar with the way the store is being used with the axios calls and when the data is refreshed. e.g. why don't we clear the list every time?
> Remove any duplicates from the notification list

- components/MainFooter.vue
- pages/index.vue
The footer in index had the options duplicated - one for desktop and one for mobile.  I've consolidated these into a single list which display differently at different breakpoints.
NB: I'm using the bootstrap functions to get the breakpoints rather than hardcoding the values in here.
> Remove the footer duplication and move into a component

- api/BaseAPI.js
- api/JobAPI.js
- api/MessageAPI.js
- store/jobs.js
For the JobAPI:
- need to pass in params in as { params } to axios calls
- get missing `status` value to use in case of error
- add extra data in APIError to match the BaseAPI style
- remove redundant try/catch in action
- don't inherit from BaseAPI (as it doesn't use anything from there)
.. I also removed the `$realPut` so it _always_ uses method overide approach now.
> A few api changes

- components/SidebarRight.vue
Resolve the TODO to make the sidebar items equal height.  When there is only one present then it should still only take up 50% of the space.
To do this I'm using flex-basis to set the initial size of each sidebar item to be 50% of the sidebar height.  I've also set flex-grow to be 0 so if there is only one item then it doesn't fill the whole 100% of space.  flex-shrink is left at the default.
> Set the initial height of the sidebar items

- components/AddressModal.vue
- components/Postcode.vue
- pages/find/index.vue
- pages/give/index.vue
Fix the TODO for postcode alignment.
The alignment of the postcode element should be dealt with by the parent rather than the postcode component itself.
> Move the centre aligning out of postcode and into the parent

- mixins/createGroupRoute.js
When there was an invalid value selected, the GroupSelect component would set the groupid back to null, and we would forget the value and reroute back to the main page...
... BUT the remembered value watcher would see the value go back to undefined, and, using the current route param (the invalid id) set it all up again, hence an infinite loop.
The fix is to understand that once we've triggered a route change we should do no more logic on this component. Once the route has changed, it'll be all fresh again :)
> Fix redirect loop in createGroupRoute mixin

- assets/css/_color-vars.scss
- components/CommunityEventModal.vue
- components/ValidatingFormInput.vue
- components/ValidatingTextarea.vue
- mixins/validationFieldHelpers.js
- mixins/validationHelpers.js
- package-lock.json
- package.json
- store/communityevents.js
So, the idea for this is to use vuelidate, I'm already familiar with it, and it's the first suggestion given on the [boostrap-vue validation page](https://bootstrap-vue.js.org/docs/reference/validation/#form-validation) too.
One of the things that it doesn't do for you is the error message handling, leaving that to you - which is a reasonable idea as there are many ways to show/display/fetch the actual error messages. The downside is it can get quite verbose and repetitive. So, I thought to create new form components that wrap the bootstrap ones to take the tedium out of it.
It basically passes everything through to the underlying component, apart from the props `validation` (the vuelidate object representing a specific field) and `validation-messages` (a map of validation type -> …
> Add form validation

- nuxt.config.js
- plugins/visibility.js
- utils/visibility.js
A first pass at a visibility watcher, re: https://app.slack.com/team/U6MA8D84T
A few random thoughts:
- maybe should include "time since last visible", as you might not want to _always_ refresh things, if it is heavy to do so
- perhaps we don't need the event timer based detection (that detects idling on the page, like maybe you left the window open for some time, then came back) - I'm not sure why we added this in karrot, maybe to support browsers that don't support visibility API (though looks not too bad, https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API#Browser_compatibility), or maybe some edge cases :/
- I made it trigger `notifications/count` and `notifications/list`, but not sure if that is correct
> Add visibility watcher

- api/BaseAPI.js
- nuxt.config.js
- pages/about.vue
- plugins/axios-baseurl.js
- store/team.js
I'm not 100% sure how it works when running on the actual server, but I _think_ this should do the trick.
Basically, we can set the axios baseURL in a plugin to be correct depending on whether we're on the server (request `IZNIK_API`) or the client (request from whatever domain we were served from).
I did sort of want to remove/combine this with the `process.env.API` configuration too, but they are not really related... so I left that one as-is.
There were two other approaches I would have liked to use, but they are not possible:
1. set the nuxt env differently depending on whether we are server or client (https://github.com/nuxt/nuxt.js/issues/6629)
2. use the nuxt/axios options which exposes `baseURL` (server) and `browserBaseURL` (client) options but doesn't place nicely with the …
> Set axios base url

- pages/settings/index.vue
- store/auth.js
As per [discussion in slack](https://freegle.slack.com/archives/C6LCTJ280/p1576002944121700?thread_ts=1575996858.120400&cid=C6LCTJ280) - just doing the simplest fix, to return data from the action.
It's slightly different to how was before as it's not the axios result object, but the data object inside it.
Confession: I did not actually try it.
(I also would have liked to remove the magic number 10 (meaning the email address needs verification), but went with the smallest possible fix)
> Return data from auth save email action

- components/LoginModal.vue
Previously it was just the opacity of the img that was being changed rather than the button actually being disabled.  I'm not setting the disabled state of the button and driving the button style change off of that.
> Set the disabled state of the social login buttons when required

- assets/css/global.scss
Quick accessibility improvements, it's generally good practice to always include hover and focus in the same ruleset for keyboard users.
> General accessibility improvements

- pages/chitchat/_id.vue
This is a refactor of the main chitchat layout to use a flexbox approach rather than the bootstrap rows and columns which were causing issues on mobile.  The layout is now much simpler.
NB: Although this fixes the margins with this section, the original issue is still present as the newsfeed itself has similar problems which I'll work on next.
> Refactor the chitchat sections to use flexbox rather than rows/cols

- nuxt.config.js
Since v1.x
see https://github.com/nuxt-community/sitemap-module/blob/dev/lib/options.js#L35-L38
> Remove deprecated option for sitemap-module

- assets/css/global.scss
- pages/spread.vue
Not sure what else to suggest for this TODO item, imo anything else is going to need a large site wide redesign in oder to incorporate the wallpaper and some sort of white wrapper around pages that are text heavy. I dont personally see anything wrong with the approach we're already using on other pages (like /help) - by default pages have the wallpaper, override where required.
As above, anything else feels like a site wide redesign with a white background container (set width) that sits on top of the wallpaper.
I do think this page needs some attention though, perhaps some sort of accordion?
> Make the /spread page white background by default

- nuxt.config.js
- package-lock.json
- package.json
- pages/councils/othercouncils.vue
- pages/councils/photosvideos.vue
- pages/councils/why.vue
- pages/index.vue
- plugins/vue-lazy-youtube-video.js
Uses latest version of lazy youtube lib, updating usage to fit new way.
Also uses esm version + transpile setting to ensure es6 doesn't sneak into the output builds.
I added `ios_saf >= 9` in our browserslist config in a vain attempt to support it, it's not enough (get  `Typeerror: Type error` in the console) but maybe helps a bit...
> Upgrade LazyYoutubeVideo and use esm version

- assets/css/global.scss
- components/NewsCommunityEvent.vue
- components/NewsReply.vue
- components/NewsUserIntro.vue
- components/NewsVolunteerOpportunity.vue
- components/ProfileImage.vue
Move the moderator "leaf" functionality into the profile-image component.  That way it can be more easily positioned over the profile image.
@edwh - You might want to check that you are happy with the size and the position.  These are now linked up to the size of the profile image so can easily be tweaked.
> Add moderator leaf image to profile picture where required.

- components/NewsAlert.vue
Fixing another one of the news components causing the padding issues on mobile.
> Remove all of the bootstrap rows/cols to sort out the mobile padding

- assets/css/global.scss
- layouts/default.vue
- pages/mydata.vue
- pages/stats/_groupname.vue
Remove the hardcoded breakpoints and use the bootstrap breakpoint functions instead.  They didn't actually correspond to the bootstrap ones anyway!
As far as I can tell you override the bootstrap versions by defining $grid-breakpoints.  When you hardcoded the values were you attempting to redefine the bootstrap ones or just have something to use in the code?  Just checking that I'm not missing anything.
> Replace hardcoded bootstrap breakpoints with bootstrap functions

- layouts/default.vue
- store/notifications.js
Whilst thinking about a refactor of the default.vue layout I've been looking at moving notifications out into a component.  Whilst doing this I've been struggling to work out what is going on and I think this might be partly due to the naming of some of the store methods.  For example there is a getter and an action both called "count".  One returns the current fetched count and the other actually gets the latest count.
Because of this I've tried to rename a few of the methods to better reflect their purpose.  So far I've just updated it in the store code and not where it is used so we can start a discussion.
> Update the naming of some of the methods in the store

- components/ChatMessageCompleted.vue
- components/ChatMessageImage.vue
- components/ChatMessageInterested.vue
- components/ChatMessagePromised.vue
- components/ChatMessageReneged.vue
- components/CommunityEvent.vue
- components/Message.vue
- components/ModImage.vue
- components/MyMessage.vue
- components/NewsAboutMe.vue
- components/NewsAlert.vue
- components/NewsMessage.vue
- components/NewsPhotoModal.vue
- components/NewsReply.vue
- components/Story.vue
- components/VolunteerOpportunity.vue
Ok this is an interesting one....
I’ve been having a think about alt text for user uploaded images after seeing your recent checkin to modImage.vue.  Basically in your checkin, all photos will have alttext of “Message photo”.  Generally this isn’t helpful at all to someone that can’t see the image.  It doesn’t provide any useful information.  
Previously I would have suggested that these type of images have empty alt text. i.e. alt=”” but after having a further read on the subject I think I’ve changed my mind.
If the image conveys information then it should have alt text. Setting alttext to be an empty string states that the image doesn’t provide any extra useful information. e.g. just an icon on a cancel button for example.  In the case that the user has uploaded an image then the …
> Remove the unnecessary alt attribute

- components/MyMessage.vue
This is a fix for the issue that @chriscant raised regarding some of the text appearing off screen in the "my posts" section on mobile.
I've given it a very brief test but just raised the draft PR for discussion.
> Move the message counts so it fits better on smaller devices

- layouts/default.vue
After investigating the IE11 issue I found a few oddities with the way the navbar was laid out.  The centre toggle with a 100% width and centre justification and the right hand nav with an auto left margin just seemed to be confusing the hell out of flexbox. I think it was probably the addition of the centre toggle that broke this in IE11.
I've just removed all the weird stuff and told the nav parent to justify the content.    I've not touched the mobile navigation.
I've tested this in IE11 on browserstack and in devtools in Chrome so this will still need a proper test on different browsers/devices.  If I don't get a chance to do this today then I'll do it tomorrow.
I thought I'd check this in as you could test it if you were desperate for a fix!
> Sort out the use of flexbox on the large navigation menu.

- components/LoginModal.vue
Semantically the sign in/up elements should be buttons and not anchors.
> Change the anchors to buttons for sign in/up

- assets/css/_color-vars.scss
- components/NoticeMessage.vue
Not sure where I got the colours from before but now these are the same colours as the bootstrap danger colours.
> Tweak the danger notice message colors

- layouts/default.vue
Only show space for the signin button when the signin button is actually required.
> Don't show the space for the signin button if not required.

- pages/find/search/_term.vue
There is an oddity on mobile view where the box is pushed to the left.  This is the same for all the elements on the page and is caused by the bootstrap grid adding some weird padding.  Because all the other elements have the same issue I've left that for now as is.
> Make the option buttons stand out

- layouts/default.vue
A small issue from the list...
Firstly I've added an underline to the selected nav item.  This fulfils the accessibility rule that colour alone shouldn't be used to signify something. If we struggle with a solution for the colours then this could be put live independently as it should help with usability.
I've tried switching the colours so that the selected item is white and the non-selected items are lighter but it's quite hard to see.  I've just done a contrast check on the regular colour and that doesn't pass AA either. i.e. #FFF on #61AE24 (white on green).  The green needs to be quite a bit darker for it to pass.  Do we have any room for tweaking the colours?  I'm guessing that green is the brand colour.
> Add underline to selected nav item

- pages/communityevents/_id.vue
- pages/volunteerings/_id.vue
This resolves the bootstrap negative margin spacing issues on smaller screens for the events and .  
In reality these whole pages really need some kind of gutters down the side and the community dropdown should probably be on it's own line and there isn't really enough room to display it next to the button.  But that's another issue...
> Correct the layout of these pages on mobile

- pages/help.vue
Currently the "contact community volunteers" button on the help page is causing layout issues on mobile.  I've shrunk the button down in size a bit and added a border around the selection to tie the form control and action button together.
> Adjust the layout and size of the contact options so it fits on mobile

- layouts/default.vue
This should fix the issue where the active page wasn't highlighted on mobile devices.  The classes were a bit weird so I've just removed some and removed the manual use of the data- attribute.  I've tried this on Chrome and on a couple of mobile devices in browserstack and it looks fine.
> Fix the active nav selection colour

- components/ExploreMap.vue
So I've just kept to the same method that you have used here for updating the map.  i.e. using the idle event.  "The internet" seem to set up a use-once event handler on idle instead but I think  I prefer what you've done here.
So basically I've just said that if you pass in a region then loop through the list of groups to get the bounds and then call fitBounds.  Pretty much the same as what you did previously.
> If we are displaying a region then make sure it's the map focus

- layouts/default.vue
I've just removed the (now) unnecessary padding which has resolved the issue.  I've given it a test in Chrome, IE11 and Safari 13.
> Correctly align the count icons

- components/GroupHeader.vue
Thought I'd add this in here for discussion.
I've moved the volunteer avatars and the button below.  Currently there are two options where one uses the bootstrap card and another with just a line break.
Thoughts?
> Tweaks to the layout on group header

- components/Autocomplete.vue
There is only one search button on this page and so the class targeting doesn't need to be so specific.
> Make the searchbutton class less specific

- pages/myposts.vue
This spelling mistake on the property was coming up in dev tools.
> Fix the spelling mistake on wanted count

- components/NewsReply.vue
Use buttons rather than spans for the news reply options.  Previously they didn't have tabstops or hovers.
All the options on this row are slightly different at the moment.  The location has one type of border (This is actually an anchor).  The message buttons don't have any focus at all.  This change at least makes it accessible and we can tidy it further later.  I need to do something about the message button too but this is generic so will need more though.  Once that is done then I'll look into making it more standard across the whole section.
> Turn the spans into proper buttons

- components/NewsReply.vue
This should resolve the edit modal issue.  I can't work out how to target an element with two classes using v-deep so I've just added an unused parent class to fix it for now.
> Only target the specific reply buttons

- assets/css/_color-vars.scss
- assets/css/global.scss
- components/NewsReply.vue
OK so I've now created a permanent button variant for this.  I've given it a test in the areas you found problems in but I will continue some more testing this afternoon.
There is one niggle I'm found which is when you hover when the button is on the blue background it is still gray.  Trying to have a see-through button which has a context sensitive hover colour would be awkward.  The only thing I could think of would be to use some kind of filter on the background colour.  So I guess it depends on how much you hate it!
> Fixes to make the light button work in other cases

- pages/find/index.vue
This was previously a button contained within an anchor so it had two tab stops.  I've now made it the same as the one on the give page
> Remove the double link/button

- components/EmailValidator.vue
- pages/find/whoami.vue
- pages/give/whoami.vue
See if this works for you.  I've changed the email validator to be in a column so it lays out correctly.  Most uses of it (like on the settings page) will lay out left aligned.  On the give and find pages I've aligned them centrally in the parent.
> Sort out the alignment of the email fields

- components/CommunityEvent.vue
- components/VolunteerOpportunity.vue
Having the title and the id connected just seemed very weird with the distance between them.  Hovering over the title also highlighted the id which was quite confusing.  I don't think this really works so I've split them up into two.
I've tested the volunteer op when it is and isn't a summary.  I've also updated the event but I don't have any to test so would be useful to have a quick check that it works ok.
> Tidy up the tab stops

- components/Autocomplete.vue
- components/Postcode.vue
This should resolve the issue raised in slack re. the width of the postcode autocomplete.
There appears to be a difference in the scoping data- attributes when directly navigating to the give page.  I have now moved the class which is used to correct this position from the postcode component into the autocomplete component.  I think this is actually a better place for it to live as it is closer to where it is actually used and makes more sense as it overrides a property in that component anyway,
> Resolve the scoping issues of the postcode styles

- assets/css/global.scss
- components/CommunityEvent.vue
- components/CommunityFeature.vue
- components/ExploreMap.vue
- components/JobsTopBar.vue
- components/Message.vue
- components/Viewed.vue
- components/VolunteerOpportunity.vue
- pages/browse/_id.vue
- pages/communityevent/_id.vue
- pages/communityevents/_id.vue
- pages/myposts.vue
- pages/settings/index.vue
- pages/spread.vue
- pages/volunteering/_id.vue
- pages/volunteerings/_id.vue
A first go at making some of the pages document structure correct.
The browse, volunteer, volunteerings, event and events pages should now have the correct structure.  I've added some headers that are screen reader only so hidden to sighted users.  The bootstrap card already provides the feature to set the element used for the titles and so I've just used that to pass in the heading level.
> Disassociate the semantic headers from the visual aspect

- layouts/default.vue
This is a bit tidier and more consistent with other uses.
> Make the notification button consistent with other similar places

- components/ChatHeader.vue
I've now left the number of rows the same but just changed the size from auto to max-content.
I've tested this in Chrome, Edge, Firefox and Safari 11 on the desktop and a Galaxy S20/Chrome and an iPhone 11/Safari.
> Resolve the row size issues in older Safari

- components/MyMessage.vue
- components/MyMessageReply.vue
I haven't given this much of a test yet but thought i'd raise a PR for discussion.
This allow the "2 days ago on FreeglePlayground #1234565" bit to wrap if necessary.  It also allows the "userid last sent" bit of replies to wrap if the username is too long.
See the slack thread for more info...  There are screenshots of the problem attached there.
Are you happy with this wrapping when it doesn't fit or would you rather truncate it?
> Allow the text to wrap so it doesn't push out the screen on mobile

- layouts/default.vue
I've now made the white foreground for dropdown toggles specific to the notification dropdown.  At the time it was only the mobile notifications button that we noticed was the wrong colour so this shouldn't affect anything else.  I've had a quick click around the pages and there isn't anything that stands out.
In the same way that I did a button tidy up so they were all defined in a single place, it might be worth doing the same thing with dropdowns as well.
> Only the notification button should have white text

- components/Autocomplete.vue
- components/PlaceAutocomplete.vue
- components/Postcode.vue
- pages/index.vue
All input fields should have an associated label.  This input had a label but it wasn't connected to the input field.
With the label and input in different components it was awkward to associate them together.  
One option would be to pass the input id into the component and use it in both the parent and child but that felt messy.  It felt right to have the label and the input together.
The awkwardness here then comes from the normal label and the screenreader label.  The two options here are pass in a couple of props or to use a slot.  A slot felt a bit overkill.  The only problem with the solution I've gone for is it's not that easy to validate that someone will pass in at least one of the two.  I suppose another way to look at it is that there is no validation on a regular input field …
> And an associated label to the autocomplete input

- assets/css/global.scss
- components/Job.vue
- components/JobsSidebar.vue
- components/JobsTopBar.vue
I've kept the same sizes but added the correct header levels when jobs are on the top and on the side.
> Sort out the header document outline for jobs

- components/AdaptiveMap.vue
Add a search role to the search field.  Not sure if this needs an input label as well.  Technically I guess all inputs need labels but to me with the search role it is pretty obvious to a screenreader what it does.  It would almost seem to get in the way having a label as well.
> Add a search role to the search field

- components/Message.vue
Something I noticed when looking into the freegled stuff.  You couldn't expand the image using the keyboard as it didn't have a tabstop or any keyboard event.
> Allow the image to be accessed via the keyboard

- components/PostMessage.vue
Add some breathing space to the gird items. 
grid-column-gap and grid-gap have actually been deprecated but we still need to support the older browsers.
> Add some space between the grid columns

- components/ChatMenu.vue
- components/NotificationOptions.vue
- layouts/default.vue
- store/notifications.js
This is a rethink of the notification options component.
Generally I'm happy with the component now although I need to give it some more testing hence the draft PR.  The only point of contention is the about me modal which I've been struggling with a bit.
So at the moment the component can only have a single element due to the way the parent is set up.  The parent in some cases is a UL and so the component can't have a wrapper DIV or it breaks the structure.
Thinking about ownership, it doesn't seem right for the about me modal to live in the notification component.  It has got nothing to do with notifications.  It just happens to be called from that component.  This modal is called from other places and these places currently also define a version of the modal. (Potential future …
> Refactor the notification options into a component

- components/ChatMenu.vue
- layouts/default.vue
- layouts/modtools.vue
- store/chats.js
- Tweaks to the chatmenu component so it's more generic
- Move chat fetching into the store rather than the layout components
- Use the chatmenu component from MT
> Chat menu refactoring for default and modtools layouts

- layouts/default.vue
- mixins/nchanHelper.js
Here it is... initially just for discussion
My main worries are around "me".  The "me" used in mounted needs to be re-defined as it won't pick up the "me" from the global mixin.  The other oddity is there is a watch over "me" as well.  This appears to work using the one from the me.js mixin but I'm a bit uncomfortable watching something that you are just assuming exists elsewhere.  Therefore I have added a local "me" property.
> Refactor the nchan logic into a mixin

- components/MainHeader.vue
- layouts/default.vue
I've pulled all of the main header stuff out into a component.  It was easy.  Maybe too easy...  It's left the HTML in default.vue pretty bare which is nice.  I've not tidied the header in any way at all.  Just transplanted it into a separate component.
I've given it a quick test but thought I'd draft PR it so I can get your thoughts before giving a more thorough test.
How do I get the "show about me" option back in notifications?  Mine appears to have gone.  I just wanted to test that it still worked.
> Refactor the main header out into a separate component

- assets/css/global.scss
- components/NotificationOptions.vue
There was code to remove the caret from the dropdown but bootstrap provide a way of doing this themselves.
> Use a better method for removing the dropdown caret

- components/JobsSidebar.vue
Not sure how long this has been incorrect for but the jobs header points to community events at the moment
> Correct the jobs link

- assets/css/typography.scss
- components/NewsReply.vue
Make the MT history section use a bigger font and then rename the typography definitions to tidy them up.
> Remove text-small as it's only used in one place

- components/MainHeader.vue
Hide the notifications icon on smaller screens when not logged in.
> Only show notifications when logged in

- components/Ratings.vue
This fixes the case inconsistency between "X freeglers gave them a thumbs up" and "Y freeglers gave them a thumbs Down".
> Fix case consistency for rating (thumbs) text
