assets/css/global.scss

I've consolidated all of the color definitions in the global file.  A lot of them are very similar but I've kept all of them for now.  All of the pages and components will now able to be updated to use these too.

Consolidate all of the color definitions in the global space

---

assets/css/_color-vars.scss
assets/css/global.scss
components/ChatBase.vue
components/ChatMessageText.vue
components/ChatPane.vue
components/ChatPopup.vue
components/CommunityEventModal.vue
components/GroupMarker.vue
components/MyMessageReply.vue
components/NewsBase.vue
components/NewsHighlight.vue
components/NewsUserIntro.vue
components/VolunteerOpportunityModal.vue
layouts/default.vue
pages/chats/_id.vue
pages/find/search/_term.vue
pages/index.vue

This is the first stab at reducing the number of colours.  I`ve removed the ones that are similar to the others and replaced them.  This still needs work but it is a bit tidier.

Remove some of the duplicate colours

---

assets/css/global.scss
components/Message.vue
components/MyMessageReply.vue
layouts/default.vue

What I`m attempting to do is basically empty out as many global classes into their local components as I can. This might lead to some more components getting created where appropriate. This will probably be done a couple of files at a time to make sure nothing gets broken.  There appears to be quite a few specificity issues so it might be tricky.  !important is used a lot.

Move some classes to a more suitable location

---

components/PostItem.vue

I`ve remove the classes that aren`t being used - I think probably just a cut and past from another place.  I`ve also removed the class that wasn`t being applied anyway due to it not having the deep selector.

Remove unused classes

---

assets/css/_color-vars.scss
components/Autocomplete.vue

Remove some colors that were being overwritten by more specific classes.  Move the used ones into the colour constants file.

Remove unused colors

---

assets/css/global.scss
components/sidebar-left.vue
components/sidebar-right.vue
pages/chitchat/_id.vue
pages/communities.vue
pages/myposts.vue

The sidebars were duplicated in three different files so I`ve put them into components.  We could go further and create a common sidebar wrapper in the future...

Create sidebar components

---

assets/css/_color-vars.scss
pages/communities.vue

Change the alert box into a regular div.
For now I`ve just created something locally in one place just to check everything works as expected.  The next stage would be to analyse what other alert boxes should be changed to see what kind of component we could create.
NB: See how using flexbox makes the HTML much simpler and easy to read.  It just sorts out all of the rows, columns, positioning etc. for you.  It`s also halved the number of elements required.

Change the alert box into a notification section

---

package-lock.json
package.json
pages/help.vue

My PR on the FAQ package has now been accepted and so the container no longer centres by default.  Therefore we can now bin the overriding of the internal class.

Update to the latest version of the FAQ package which doesn't centre

---

LICENCE

Assuming the readme is correct I've added in a GPL v2 licence file

Add GPL v2 licence file

---

assets/css/global.scss

Unless I`m missing something then I can`t see this class being used anywhere.

Remove unused class

---

components/Autocomplete.vue
store/messages.js
store/newsfeed.js

I just changed them "blind" without trying anything out...
If you're comfortable with that, merge away, otherwise I'll need to work out how to test those scenarios.

Replace JSON stringify then parse with cloneDeep

---

components/GroupRememberSelect.vue

Probably only added for some debugging...

Remove pointless wrapper div

---

components/ChatPane.vue
components/ProfileModal.vue
store/user.js

This is currently done in a few places.  Maybe we could add a function in the user store to do this?

Create a computed method to check if the user has reneged

---

components/GroupHeader.vue
pages/chats/_id.vue
pages/find/whatnext.vue
pages/give/whatnext.vue

This was throwing a warning as it was being passed as a string without the v-bind

Need to tell Vue this is an expression rather than a string

---

components/NewsNoticeboard.vue
pages/settings/index.vue

This should be the final b-alert/notice replaced with the notice message component.  The others weren't too tricky after all.

Replace the b-alert with a notice-message component

---

.gitignore
nuxt.config.js
package-lock.json
package.json

Adds ability to disable eslint autofixing.
If you want eslint autofix do nothing, it will work as before.
If you DO NOT want eslint auto fix, add a `.env` file in the root of the project with the contents:
```
DISABLE_ESLINT_AUTOFIX=true
```

Allow disabling of eslint autofix with local conf

---

nuxt.config.js

My original version was rubbish.

Fix eslint autofix configuration with no .env

---

assets/css/global.scss
components/NewsReply.vue
components/NewsThread.vue

Use the bootstrap breakpoints where necessary.
I've added comments for other places to do this i.e. the profile classes.  I might break the profile image stuff out into a component next so I'll sort the breakpoints for those classes then.

Use bootstrap breakpoints

---

components/LoginModal.vue

So I've backtracked a little on the stuff I was doing on the login form.  There are potentially a lot of questions etc. in that area so I thought I would strip it down to basics and do a step at a time.
This change just updates the current input field with placeholder into an accessible input field with associated label.  Are you happy with this style?  The benefits you get here are:
- The field works correctly with a screenreader
- You can click the label to focus on the field which is great for people with motor issues
- Placeholder text isn't automatically translated by browsers; the label is.
Do we need to keep the pre-pended "Your" on the fields? i.e. "Your email address", "Your password", "Your name" etc.  My personal opinion is that I think it makes it harder to scan for the words …

Update the login form fields to have an associated label.

---

assets/css/global.scss
components/CommunityEventModal.vue
components/ValidatingForm.vue
components/VolunteerOpportunityModal.vue

Ok, this makes it very similar to the community event validation.
It's quite hard to check if it's all ok, I created a volunteer op, but needs to be approved....
I moved the shared form styles into the global scss file, that involved import bootstrap functions and variables, what do you think @JayyajGH?

Add validation for volunteer ops

---

pages/chitchat/_id.vue

Bootstrap rows and columns should live in a bootstrap container.
https://bootstrap-vue.js.org/docs/components/layout/

Add a bootstrap container to house the rows and columns

---

pages/stats/_groupname.vue

Stats card heights

---

components/NewsAlert.vue

This resolves another issue with the gap on the right hand screen of the screen on mobile

Resolve another mobile padding issue

---

pages/find/whatnext.vue
pages/give/whatnext.vue

As per slack
"Stack, I think, with "something else" top and variant success. The opposite option next and variant primary. Then others below and white."
You may want to pull this down and take a look before merging to make sure you're happy though

Reposition whatnext buttons

---

assets/css/global.scss

Add a comment to describe the issue with overriding bootstrap variables

---

components/ChatMessageModMail.vue
components/NotificationCommentOnComment.vue
components/NotificationCommentOnPost.vue
components/NotificationLovedComment.vue
components/NotificationLovedPost.vue

Here is another set of refactoring to use the profile image component. 
THESE ARE CURRENTLY UNTESTED
Is there an easy way to test them?

Use the profile component

---

pages/about.vue
pages/settings/index.vue

Remove two unused brokenImage methods that I forgot to remove when I added the profile-image component.

Remove unused brokenImage methods

---

components/ProfileImage.vue

Does this improve things Edward?  Just checked and it looks like it was 15px before on mobile which is probably where I got the size from.

Increase the size of the small profile image on small screens

---

components/NewsVolunteerOpportunity.vue

Hopefully this might be the last one!

Remove bootstrap rows/cols to resolve mobile padding issues

---

assets/css/_color-vars.scss
assets/css/global.scss
components/Autocomplete.vue
components/AvailabilityModal.vue
components/LoginModal.vue
components/Message.vue
components/WizardProgress.vue
layouts/default.vue
pages/stats/authority/_id.vue

Move a bunch more colours into the colour file.  I've not done any consolidation as part of this.  I've just moved their definitions into the common location.  It might be able time for us to see if we can chop any out.

Move all remaining colour variables into the colour file.

---

components/ChatMessageDateRead.vue
components/ChatMessagePromised.vue
components/GroupHeader.vue
components/MyMessageReply.vue
components/NewsReply.vue
components/Notification.vue
components/NotificationAboutMe.vue
components/NotificationCommentOnComment.vue
components/NotificationExhort.vue
components/NotificationMembershipApproved.vue
components/NotificationMembershipPending.vue
components/SidebarLeft.vue

Move some inline styles into classes.

Remove some inline styles

---

components/ChatMessageText.vue
nuxt.config.js

Some of the logic in the HTML in this component was complex and duplicated so I have refactored it out into computed props.  It makes the HTML much nicer to read now too.

Refactor some of the more complex logic in the HTML into computed props.

---

pages/find/search/_term.vue

The "Post a WANTED" button was a button within an anchor.  It should just be an anchor.  Also sort out the duplicate elements and just makes the classes conditional.

Sort out the anchor semantics and tidy the classes

---

components/LocalStorageMonitor.vue
layouts/default.vue

Move the local storage functionality into a component to start to tidy up the default layout

Move the local storage checks into a component

---

layouts/default.vue
plugins/visibility.js
store/notifications.js

Hopefully this now reflects the meaning of count better.  Sorry I missed the visibility update on my previous PR.

Rename count to be unreadCount

---

pages/disclaimer.vue
pages/privacy.vue
pages/terms.vue

More design shrapnel stuff.  Is there any reason the privacy container has a white background and the others don't?

Tidy the three containers

---

assets/css/_color-vars.scss

Slightly adjust the notice warning colours to make it more readable

---

components/ProfileModal.vue
pages/profile/_id.vue

Revert the changes to use the new profile component here.

Revert the changes due to accidental promotion.

---

components/ChatBase.vue
components/GroupProfileImage.vue
components/NewsBase.vue
components/NewsPhotoModal.vue
components/NewsReply.vue
components/NotificationExhort.vue
components/ProfileImage.vue

Use require when loading static images so it also works on mobiles.

Update image loading to use require so it works on mobiles

---

layouts/default.vue
store/notifications.js

Move some notifications logic out of the view and into the store with the getters.

Refactor some of the notification logic into the store

---

components/NewsCommunityEvent.vue

Another one of these where it adds right padding on mobile and messes up the layout.

Tidy the layout so it works on mobile

---

layouts/default.vue

I am struggling to refactor the notifications out of default.vue due to various issues so thought I`d do it bit by bit.  This is the removal of an unnecessary block element contained within an inline element.

Remove the block element contained within the inline element

---

components/PasswordEntry.vue

A small tidy of the showpassword  icons and a tweak to the border colour so it fits in better.

Tidy the showpassword icon element layout

---

pages/help.vue

A few small tweaks to tidy up the contact section.
re. slack - I can either change the text and make the button bigger again or leave this as it is.

Streamlining of the button code

---

components/GroupHeader.vue

Make the mail to elements more accessible.  They were previously  buttons contained within links so I've changed them just to be links.

Make the mailto element a link rather than a button within a link

---

components/CovidPostWarning.vue
plugins/vue-awesome.js

Here is one option with regards to making the checkbox more obvious.
I've just styled the bootstrap version to be a bit bigger.  This would need some messing with alignment of the text too but I just thought I'd show you to see if you think it's any better than what is there currently.

Style the bootstrap checkbox

---

layouts/default.vue

This is an idea for how the navbar could be better laid out without crushing the longer text.  I've basically let flexbox deal with the layout.  This is currently untested but just to give an impression of how it will look.

Better align the nav icons

---

layouts/default.vue

Slightly tweak the position of the notification badge

Change the position of the notification badge

---

components/CommunityEventModal.vue
components/CovidSafeFreegling.vue
components/CovidWarning.vue
components/DonationButton.vue
components/ExploreMap.vue
components/ExternalLink.vue
components/GroupHeader.vue
components/ModDashboardPopularPosts.vue
components/ModHelpPublicity.vue
components/ModMissingFacebook.vue
components/ModMissingTwitter.vue
components/ModSettingsGroup.vue
components/ModSupportAddGroup.vue
components/ModSupportFindGroup.vue
components/ModSupportUser.vue
components/VolunteerOpportunityModal.vue
layouts/modtools.vue
pages/help.vue

I'm adding an ExternalLink component and altering almost all of the external links to use it.
This should allow the iOS apps to open such links in the external Safari browser.
And fixed one wee bug along the way.

External links

---

assets/css/global.scss
pages/help.vue

Fix the colour of the "find out more" button on the help page

Use variant rather than the direct class

---

assets/css/global.scss

If you right click on an anchor styled as a button then you got the default bootstrap styling.

Add colours for active state

---

components/CommunityEventSidebar.vue
components/VolunteerOpportunitySidebar.vue

Various accessibility and HTML improvements to the volunteer sidebar
- Remove block element within an inline element (h4 within a)
- The tabbing order was incorrect due to the button being floated
- The focus rectangle for the header was around the header and the button
- Add a meaningful aria label to the button rather than "Add"

Accessibility and HTML improvements

---

components/SettingsGroup.vue

What do you think about this?
The slight delay in the Vue model (Vue view model????) getting updating actually provides a slight transition so it actually feels quite smooth.  The only slightly weird thing is the blue focus indicator doesn't go well with the green colour but that's a completely different issue!

Make it obvious if the email dropdown has a positive selection

---

components/SettingsGroup.vue

I've now made this a computed prop which I think looks much nicer and means it can be commented and reads better.  Also noticed the default grey border was too thick.

Tidy up the email frequency class code

---

components/CommunityEvent.vue
components/CommunityEventSidebar.vue
components/CommunityFeature.vue
components/ModCommunityEvent.vue
components/ModVolunteerOpportunity.vue
components/SidebarSection.vue
components/VolunteerOpportunity.vue
components/VolunteerOpportunitySidebar.vue
pages/communityevent/_id.vue
pages/communityevents/_id.vue
pages/volunteering/_id.vue
pages/volunteerings/_id.vue

So I've pulled out the duplicate code in these two components.  I don't think the thing you mentioned on the other PR is relevant here as the separate modals handle that.
The only thing I'm not happy with here yet is the name of the component and the names of some of the props.  Basically I need a name for something that can be an event or an opportunity.  Any ideas?

Refactor the common parts from the sidebar items

---

components/Message.vue

I noticed that I had got my rows a little incorrect so I've fixed them.  Grid was just putting them in the right order anyway so it shouldn't matter but this is more explicit.

Correct the grid layout for the options

---

pages/myposts.vue

This resolves the issue with the myposts screen being too wide on mobile

Remove the bootstrap rows as they cause the screen to be too wide

---

components/CommunityEvent.vue
components/VolunteerOpportunity.vue

Fix the mobile layout by replacing the bootstrap rows/cols with flexbox

Remove the bootstrap rows to fix the mobile sizing issue.

---

pages/find/whatnext.vue
pages/give/whatnext.vue

Fix the mobile row/col issue shimmy on the give page.

Remove the bootstrap rows/cols to fix the mobile shimmy

---

layouts/default.vue

This was a tweak I made when looking at tidying up default.vue before I went on holiday.  Basically it just uses a single class rather than two classes so might make refactoring this page slightly simpler. Like 0.001% simpler.

Tidy up the notification badge classes

---

layouts/default.vue

Left in in a previous commit and now keeps getting flagged!

Remove extra space

---

pages/chats/_id.vue

More accessibility improvements.  All inputs should have a label and the search box should have a landmark search role.

Add a landmark role to make the search box more accessible

---

components/CovidCheckList.vue
components/CovidSafeFreegling.vue
components/Message.vue
components/ModLog.vue
pages/find/index.vue
pages/give/index.vue

This is not confirmed as something we'll do yet; it's to help discussion.

Possible COVID checklist for discussion

---

components/NumberIncrementDecrement.vue

A few accessibility improvements for the spin button

Here are a few accessibility tweaks

---

assets/css/buttons.scss
assets/css/global.scss

Move anything button related into a separate file.  I've not tidied anything yet.  Just moved it.

Move anything button related into a separate file

---

components/NotificationOptions.vue

Shuffle the notification dropdown when on smaller screens so it fits

---

assets/css/global.scss
package-lock.json
package.json

If you prefer it then merge it.  If you don't then I'll delete it. :-)
It's still messy but will plug the hole and explain why we're plugging the hole until we find the best solution that will work in all places.

Better temp fix for icon alignment issues

---

components/NewsReply.vue

Change from the sonar.io findings.
This data isn't really a table.  It's just a two column layout so I've changed it to use flexbox.

Replace the table with regular divs

---

static/robots.txt

Add robots file

---

components/AdaptiveMap.vue

When written in caps a sr reads out OFFER and WANTED as the individual letters.

Uncapitalise the text as it is read out strangely

---

assets/css/global.scss

How about this for a very basic dark-mode?

Basic dark-mode implementation
